/**:
  ros__parameters:

    # Latitude of local origin
    # latitude: 40.81187906
    latitude: 0.0

    # Longitude of local origin
    # longitude: 29.35810110
    longitude: 0.0

    # Altitude of local origin
    # altitude: 47.62
    altitude: 0.0
